### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lemuscanovas** [lemuscanovas/synoptReg#5]
- [x] introduir t.test per a sign anomalies
- [x] Introduir mètode SOM
- [ ] funció WT dominant
- [ ] Crear funció de descàrrega emprant `ecmwfr`
- [ ] Crear funció de lectura ReadNetCDF, amb lectura eficient per dimensió.
- [ ] Introduir un mètode oriented-validation approach (S-mode i Lamb)
- [ ] Introduir mètode futur PXE
- [ ] Crear app user-friendly amb shiny 
- [ ] Introduir una metodologia de detecció de CE a l'escala sinòptica. Mirar Sánchez-Benítez et al. (2019)
- [ ] Introduir resampling bootstrap per a una significació estadística de les anomalies
